name: GitHub Actions
run-name: ${{ github.actor }} is pushing GitHub Actions 🚀
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules with Node.js ${{ matrix.node-version }}
        run: npm install
      - name: build prod
        run: npm run build:prod
      - name: TS lint
        run: npm run lint:ts
      - name: SCSS lint
        run: npm run lint:scss
      - name: UNIT test
        run: npm run test:unit
